version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - chmod +x $CODEBUILD_SRC_DIR/build.sh
      - $CODEBUILD_SRC_DIR/build.sh int-test
      - $CODEBUILD_SRC_DIR/build.sh deploy dev
      - $CODEBUILD_SRC_DIR/build.sh acceptance-test